server:
  port: 8080

spring:
  application:
    name: api-gateway  # Service name for Eureka registration
  config:
    import: "configserver:"  # Fetch configuration from the Config Server
  cloud:
    config:
      uri: http://localhost:8888  # Config Server URI
      fail-fast: true  # Fail fast if Config Server is unavailable
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE  # Route to the Auth Service
          predicates:
            - Path=/auth/**  # Match paths starting with /auth

        - id: user-service
          uri: lb://USER-SERVICE  # Route to the User Service
          predicates:
            - Path=/user/**, /admin/**  # Match paths starting with /user or /admin
          filters:
            - TokenRelay=  # Relay the OAuth2 token to the downstream service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
  instance:
    prefer-ip-address: true  # Register with IP address instead of hostname
